<a href="https://colab.research.google.com/github/jaeohshin/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hola I am excited to learn pytorch")

Hola I am excited to learn pytorch


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


In [ ]:
## Introduction to Tensors
##
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back as Python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7, 7, 6])
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
#MATRIX
MATRIX = torch.tensor([ [7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3], 
                        [3, 6, 9],
                        [2, 4, 6]],
                       [[2, 3, 4], 
                        [4, 7, 10],
                        [3, 5, 7]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4,  6]],

        [[ 2,  3,  4],
         [ 4,  7, 10],
         [ 3,  5,  7]]])

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
#sec. 13 of youtubevideo

In [ ]:
### Random tensors

### Random tensors

Why random tensors?

Random tensors are improtant because the way many neural networks learn is that they start with tensorsfull of random numbers and then adjust to better repreent the data.


In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4177, 0.1552, 0.8011, 0.5060],
        [0.7827, 0.5365, 0.4653, 0.6538],
        [0.4538, 0.2178, 0.9042, 0.4998]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
### Zeros and ones

zeros_tensor = torch.zeros(size=(3,4))
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros_tensor*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Create a range of tensors andtensors-like


In [ ]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Tensorslike

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)

In [ ]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Element-wise multiplication

In [ ]:
tensorA = torch.tensor([1, 2, 3])
tensorB = torch.tensor([3, 1, 5])
tensorA * tensorB

tensor([ 3,  2, 15])

In [ ]:
torch.matmul(tensorA, tensorB)

tensor(20)

In [ ]:
torch.matmul(torch.rand(3,2).T, torch.rand(3,3))

tensor([[0.2140, 0.1345, 0.2784],
        [0.7449, 0.8275, 0.8642]])

In [ ]:
tensorA.argmax()

tensor(2)

In [ ]:
tensorA[2]

tensor(3)

Torch Stack

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z = x.view(3,3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]), torch.Size([3, 3]))

In [ ]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x],dim=0)

In [ ]:
x_stacked, x_stacked.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([4, 9]))

Squeeze, Unsqueeze


In [ ]:
x = torch.zeros(2, 3, 2)

In [ ]:
x, x.shape

(tensor([[[0., 0.],
          [0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.],
          [0., 0.]]]), torch.Size([2, 3, 2]))

In [ ]:
x = torch.randn(2, 3, 5)

In [ ]:
x.size()

torch.Size([2, 3, 5])

In [ ]:
torch.permute(x, (2, 0, 1)).size()

torch.Size([5, 2, 3])

Indexing (selecting data from tensors)


In [14]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [2]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
x[0][0][0]

tensor(1)

In [5]:
x[:,1,2]

tensor([6])

In [6]:
x[0, 0, :]

tensor([1, 2, 3])

Numpy to tensor or vice versa

In [9]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor

tensor([1., 1., 1., 1., 1., 1., 1.])

In [10]:
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [11]:
torch.rand(3, 3)

tensor([[0.7966, 0.9215, 0.6639],
        [0.8621, 0.6039, 0.4458],
        [0.6233, 0.9053, 0.3756]])

In [19]:
import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_C)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [1]:
!nvidia-smi

Fri Mar 10 01:07:26 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P0    27W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_C)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


GPU