<a href="https://colab.research.google.com/github/jaeohshin/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hola I am excited to learn pytorch")

Hola I am excited to learn pytorch


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


In [ ]:
## Introduction to Tensors
##
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back as Python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7, 7, 6])
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
#MATRIX
MATRIX = torch.tensor([ [7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3], 
                        [3, 6, 9],
                        [2, 4, 6]],
                       [[2, 3, 4], 
                        [4, 7, 10],
                        [3, 5, 7]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4,  6]],

        [[ 2,  3,  4],
         [ 4,  7, 10],
         [ 3,  5,  7]]])

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
#sec. 13 of youtubevideo

In [ ]:
### Random tensors

### Random tensors

Why random tensors?

Random tensors are improtant because the way many neural networks learn is that they start with tensorsfull of random numbers and then adjust to better repreent the data.


In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)