<a href="https://colab.research.google.com/github/jaeohshin/ML-with-Pytorch/blob/main/lab1_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import math

In [2]:
print(torch.version)

<module 'torch.version' from '/usr/local/lib/python3.10/dist-packages/torch/version.py'>


In [3]:
t1 = torch.zeros(4,3)

In [4]:
print(t1)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [5]:
print(t1.shape)

torch.Size([4, 3])


In [6]:
print(t1.dtype)

torch.float32


In [7]:
print(t1.device)

cpu


In [8]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
t1_gpu = t1.cuda(device)
print(t1_gpu.device)
print(t1.device)

cuda:0
cpu


In [3]:
x = torch.tensor(-2.0, requires_grad = False)
y = torch.tensor(5.0, requires_grad = True)
z = torch.tensor(-4.0, requires_grad = True)
f = (x+y) * z

f.backward()

print(x.grad)
print(y.grad)
print(z.grad)

None
tensor(-4.)
tensor(3.)


In [16]:
t1 = torch.rand(12)
print(t1.shape)
print(t1)

torch.Size([12])
tensor([0.2019, 0.9764, 0.4328, 0.9827, 0.4753, 0.4698, 0.5838, 0.3277, 0.2467,
        0.1448, 0.7609, 0.1729])


In [17]:
print("\n----------after unsqueeze-------")
t1 = t1.unsqueeze(0)
print(t1.shape)
print(t1)


----------after unsqueeze-------
torch.Size([1, 12])
tensor([[0.2019, 0.9764, 0.4328, 0.9827, 0.4753, 0.4698, 0.5838, 0.3277, 0.2467,
         0.1448, 0.7609, 0.1729]])


In [19]:
print("\n----------after reshape-------")
t1 = t1.reshape(3, 2, 2)
print(t1.shape)
print(t1)


----------after reshape-------
torch.Size([3, 2, 2])
tensor([[[0.2019, 0.9764],
         [0.4328, 0.9827]],

        [[0.4753, 0.4698],
         [0.5838, 0.3277]],

        [[0.2467, 0.1448],
         [0.7609, 0.1729]]])


In [20]:
print("\n----------after permute-------")
t1 = t1.permute(1, 2, 0)
print(t1.shape)
print(t1)


----------after permute-------
torch.Size([2, 2, 3])
tensor([[[0.2019, 0.4753, 0.2467],
         [0.9764, 0.4698, 0.1448]],

        [[0.4328, 0.5838, 0.7609],
         [0.9827, 0.3277, 0.1729]]])
